Prohibit use of request_uri
openid/federation pull request #119
Opened 2024-10-26 22:15 UTC by selfissued

Fixes #114

2024-10-28 05:07 UTC, vdzhuvinov requested changes
All good, just a typo that needs fixing. Thanks!

2024-10-28 05:07 UTC, vdzhuvinov commented on openid-federation-1_0.xml
> +	  <spanx style="verb">request_uri</spanx> request parameter) parameter
Repeating parameter.

2024-10-28 07:35 UTC, rohe approved these changes
Provided @vdzhuvinov change request is honoured.

2024-10-28 16:10 UTC, selfissued commented on openid-federation-1_0.xml
> +	  <spanx style="verb">request_uri</spanx> request parameter) parameter
Corrected

2024-10-28 16:15 UTC, vdzhuvinov approved these changes

2024-10-30 15:30 UTC, selfissued commented
On the 30-Oct-24 Federation editors' call, @ve7jtb suggested the possibility of using HTTP to limit the size of resources received.

Mike said that these OP metadata parameters may be pertinent:
> request_uri_parameter_supported
> OPTIONAL. Boolean value specifying whether the OP supports use of the request_uri parameter, with true indicating support. If omitted, the default value is true.
> require_request_uri_registration
> OPTIONAL. Boolean value specifying whether the OP requires any request_uri values used to be pre-registered using the request_uris registration parameter. Pre-registration is REQUIRED when the value is true. If omitted, the default value is false.

2024-10-31 04:45 UTC, selfissued commented
During the 30-Oct-24 Federation editors' call, John was skeptical of removing an OpenID Connect feature.  He suggested ways to mitigate the denial-of-service problems instead, including at the HTTP layer.

2024-11-04 15:57 UTC, peppelinux approved these changes

2024-11-04 16:29 UTC, merged