Define entity_statement_signing_alg_values_supported metadata parameter
openid/federation pull request #81
Opened 2024-09-07 23:51 UTC by selfissued

Fix #65 

Cc: @Razumain

2024-09-09 07:20 UTC, vdzhuvinov requested changes

2024-09-09 07:20 UTC, vdzhuvinov commented on openid-federation-1_0.xml
> +	      If omitted, the default value is <spanx style="verb">["RS256"]</spanx>.
On its own, the definition of this parameter is okay. However, having this parameter parameter defined would not be sufficient for the entities in a federation to be able to use a specific JWS algorithm when the more than one is supported. People will ask - what do we do then with this parameter? How do I get an ES signed with say ES256 when RS256 and ES256 are supported?

2024-10-23 13:40 UTC, peppelinux approved these changes

2024-10-23 13:55 UTC, vdzhuvinov commented
Last time when we discussed this (and I was present), there were two solutions.

Both solutions have this metadata parameter, that lists the supported JWS algs for entity statements.

The difference is:

1. Entities Statements can be signed with any of the supported JWS algs. There is no method to request the issue of an Entity Statement with a given JWS alg. This means consumers must be prepared to handle all JWS algs that are supported.

2. Entity Statements are normally signed with a default JWS alg, but there is also the possibility to request a specific JWS alg using a query param like `jws_alg=ES256`. With that consumers have a mean to control the signature algorithm.

Solution 1 seems simpler, in terms of specification and API.

Solution 2 has the benefit that in multi anchored / lateral federations, where one of the federations supports additional JWS algs, but the algs still intersect (there is a commonly supported JWS alg, like RS256), consumers will be able to collect Entity Statements with an alg that they can work it. Otherwise they won't be able to do this.

2024-10-23 16:39 UTC, selfissued commented
As discussed on today's Federation editors' call, we would want actionable guidance on how and when to use this parameter before including this feature in the specification.

2024-10-30 15:20 UTC, rohe approved these changes

2025-05-08 19:18 UTC, selfissued commented
Closing on the same basis as #65

2025-05-08 19:18 UTC, closed without merging