Describe validation of resolved metadata
openid/federation pull request #96
Opened 2024-09-22 00:49 UTC by selfissued

Fixes #28

2024-09-25 09:12 UTC, vdzhuvinov requested changes
Just minor comment to clarify who is doing the resolved metadata validation :)

2024-09-25 09:12 UTC, vdzhuvinov commented on openid-federation-1_0.xml
> +		Likewise, the Entity MUST verify that
the Entity -> the Trust Chain subject

2024-09-25 09:12 UTC, vdzhuvinov commented on openid-federation-1_0.xml
> +		all the required metadata parameters for its Entity Type are present
Entity Type -> Entity Types

2024-09-29 21:48 UTC, peppelinux approved these changes

2024-10-02 08:21 UTC, MichaelFraser1999 approved these changes

2024-10-02 14:13 UTC, merged